// Drink data. Each step: type drives the animation + sound, ratio sizes the layer.
// ratio values within a drink sum to ~100 (visual proportion of the final vessel).

export const ADDONS = {
  cocoa:     { label: 'Cocoa dust',    visual: 'sprinkle', color: '#5a3a22', sound: 'dust',   note: 'A dusting of cocoa over the foam' },
  cinnamon:  { label: 'Cinnamon',      visual: 'sprinkle', color: '#8a5a2e', sound: 'dust',   note: 'Ground cinnamon, warm and sweet' },
  cream:     { label: 'Whipped cream', visual: 'dollop',   color: '#faf5ea', sound: 'froth',  note: 'A cloud of whipped cream' },
  icecream:  { label: 'Ice cream',     visual: 'scoop',    color: '#f3e9d2', sound: 'thud',   note: 'A scoop of vanilla ice cream' },
  hazelnut:  { label: 'Hazelnut',      visual: 'syrup',    color: '#7a4a26', sound: 'syrup',  note: '10 ml hazelnut syrup' },
  vanilla:   { label: 'Vanilla',       visual: 'syrup',    color: '#e8d9a8', sound: 'syrup',  note: '10 ml vanilla syrup' },
  caramel:   { label: 'Caramel',       visual: 'syrup',    color: '#b06a28', sound: 'syrup',  note: 'A drizzle of caramel' },
  protein:   { label: 'Protein',       visual: 'dust',     color: '#d8cbb2', sound: 'dust',   note: 'A scoop of protein, blended in' },
  extrashot: { label: 'Extra shot',    visual: 'shot',     color: '#1f1208', sound: 'espresso', note: 'Another 30 ml of espresso' },
  ristretto: { label: 'Ristretto',     visual: 'tag',      color: '#1f1208', sound: 'blip',   note: 'Short pull - sweeter, more intense' },
  decaf:     { label: 'Decaf',         visual: 'tag',      color: '#8f867a', sound: 'blip',   note: 'Same ritual, no caffeine' },
};

const C = {
  espresso: '#2a1708', espressoEdge: '#4a2c12', crema: '#8a5a28',
  milk: '#d9bf9f', foam: '#f2e7d2', water: '#3d4a52', choc: '#3a1f0e',
  coldbrew: '#241408', frappe: '#6b4a2a', ice: '#cfe4ec',
  gin: '#dfe9e4', vodka: '#e8ecea', rum: '#e8e4d2', tequila: '#eee6c8', whiskey: '#c47f2a', jager: '#3a1c10',
  vermouth: '#e4dcc0', oj: '#e8963a', gingerbeer: '#d8a24a', tonic: '#dce8e4', soda: '#dce8e4',
  lime: '#9ec24a', energy: '#c8d44a', mint: '#4a7a3a', sugar: '#f0ead8', bitters: '#8a4a1a', triplesec: '#e8c88a',
  sweetvermouth: '#5c1e14', campari: '#d8401f', aperol: '#f26a2e', prosecco: '#e9dfa4', cranberry: '#a8202e',
  grenadine: '#c11f3a', coconut: '#f4eeda', pineapple: '#eec84e', coffeeliq: '#20100a', tomato: '#b03220',
  cola: '#1d0d06', redwine: '#6e1423', condensed: '#efe3c4', brewed: '#2b1608', lemon: '#e8d44f', darkrum: '#3a2410',
};

export const DRINKS = {
  coffee: [
    { id: 'espresso', name: 'Espresso', temp: 'hot', vessel: 'demitasse', tagline: 'The pure shot. Everything starts here.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 100, color: C.espresso, edge: C.crema, sound: 'espresso', note: '18 g of fine grounds, 9 bars of pressure, 25-30 seconds' },
      ],
      method: 'Finely ground coffee is tamped into the portafilter and hot water is forced through at 9 bars. The golden crema on top is the sign of a good pull.',
      addons: ['ristretto', 'decaf', 'extrashot'] },
    { id: 'ristretto', name: 'Ristretto', temp: 'hot', vessel: 'demitasse', tagline: 'The short pull - sweeter and stronger.',
      steps: [
        { type: 'espresso', label: 'Ristretto shot', amount: '20 ml', ratio: 100, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Same 18 g dose, half the water - pulled in 15 seconds' },
      ],
      method: 'Ristretto means "restricted" - the same coffee dose as an espresso but half the water. Less bitter, more syrupy, the sweetest expression of the bean.',
      addons: ['decaf', 'extrashot'] },
    { id: 'doppio', name: 'Doppio', temp: 'hot', vessel: 'demitasse', tagline: 'Two shots, one cup. The modern standard.',
      steps: [
        { type: 'espresso', label: 'Double espresso', amount: '60 ml', ratio: 100, color: C.espresso, edge: C.crema, sound: 'espresso', note: '18-20 g of grounds, a 25-30 second pull, twice the volume' },
      ],
      method: 'Doppio simply means "double". When a cafe menu says espresso today, it usually means this - a double shot is the base of almost every drink on this list.',
      addons: ['ristretto', 'decaf'] },
    { id: 'lungo', name: 'Lungo', temp: 'hot', vessel: 'demitasse', tagline: 'The long pull - more water, more bite.',
      steps: [
        { type: 'espresso', label: 'Lungo shot', amount: '90 ml', ratio: 100, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'The same dose pulled for 45-60 seconds' },
      ],
      method: 'Lungo means "long" - the shot is pulled with up to twice the water. Milder body than espresso, more bitterness, slightly more caffeine.',
      addons: ['decaf', 'extrashot'] },
    { id: 'conpanna', name: 'Espresso con Panna', temp: 'hot', vessel: 'demitasse', tagline: 'A shot under a cloud of cream.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 60, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot in a small cup' },
        { type: 'foam', label: 'Whipped cream', amount: 'a dollop', ratio: 40, color: '#faf5ea', sound: 'froth', note: 'Con panna means "with cream"' },
      ],
      method: 'A double espresso topped with a dollop of whipped cream. The cream melts into the crema sip by sip - dessert in a demitasse.',
      addons: ['cocoa', 'decaf'] },
    { id: 'macchiato', name: 'Macchiato', temp: 'hot', vessel: 'demitasse', tagline: 'Espresso, "stained" with foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 72, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot, pulled short' },
        { type: 'foam', label: 'Milk foam', amount: 'a spoonful', ratio: 28, color: C.foam, sound: 'froth', note: 'Just a stain of foam - macchiato means "stained"' },
      ],
      method: 'A straight espresso marked with a spoonful of milk foam. The foam softens the edge without diluting the shot.',
      addons: ['cocoa', 'cinnamon', 'ristretto', 'decaf', 'extrashot'] },
    { id: 'cortado', name: 'Cortado', temp: 'hot', vessel: 'glass-small', tagline: 'Half espresso, half warm milk. No foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 50, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'The base double shot' },
        { type: 'milk', label: 'Steamed milk', amount: '30 ml', ratio: 50, color: C.milk, sound: 'pour', note: 'Steamed, not frothed - equal parts' },
      ],
      method: 'Equal parts espresso and steamed milk. The milk is warm and silky with almost no foam, cutting the acidity in half.',
      addons: ['vanilla', 'hazelnut', 'decaf', 'extrashot'] },
    { id: 'piccolo', name: 'Piccolo Latte', temp: 'hot', vessel: 'glass-small', tagline: 'A baby latte. Small glass, big flavor.',
      steps: [
        { type: 'espresso', label: 'Ristretto', amount: '20 ml', ratio: 36, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A restricted shot keeps it sweet in a small glass' },
        { type: 'milk', label: 'Steamed milk', amount: '60 ml', ratio: 64, color: C.milk, sound: 'pour', note: 'Silky steamed milk to the top of a 90 ml glass' },
      ],
      method: 'A ristretto shot topped with steamed milk in a small glass. All the balance of a latte at tasting size - piccolo means "small" in Italian.',
      addons: ['vanilla', 'decaf', 'extrashot'] },
    { id: 'flatwhite', name: 'Flat White', temp: 'hot', vessel: 'mug', tagline: 'Velvet microfoam over a double shot.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 33, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double ristretto is the classic base' },
        { type: 'milk', label: 'Microfoam milk', amount: '130 ml', ratio: 67, color: C.milk, sound: 'pour', note: 'Steamed to a velvet texture - no dry foam' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.foam, sound: 'blip', note: 'The pour finishes with a rosetta or heart' },
      ],
      method: 'A double shot topped with microfoam - milk steamed so finely it pours like wet paint. Stronger than a latte, silkier than a cappuccino.',
      addons: ['cocoa', 'vanilla', 'hazelnut', 'caramel', 'ristretto', 'decaf', 'extrashot'] },
    { id: 'cappuccino', name: 'Cappuccino', temp: 'hot', vessel: 'mug', tagline: 'The rule of thirds: espresso, milk, foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 33, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'One third of the cup' },
        { type: 'milk', label: 'Steamed milk', amount: '60 ml', ratio: 33, color: C.milk, sound: 'pour', note: 'The second third' },
        { type: 'foam', label: 'Milk foam', amount: '60 ml', ratio: 34, color: C.foam, sound: 'froth', note: 'A thick, airy cap - the final third' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.espresso, sound: 'blip', note: 'Often finished with a dusting or art' },
      ],
      method: 'Perfect thirds: espresso, steamed milk, and a deep cap of airy foam. The foam is what separates it from a latte.',
      addons: ['cocoa', 'cinnamon', 'vanilla', 'hazelnut', 'caramel', 'decaf', 'extrashot'] },
    { id: 'latte', name: 'Caffè Latte', temp: 'hot', vessel: 'mug', tagline: 'Mostly milk, gently coffee.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 18, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Just one shot in a big cup' },
        { type: 'milk', label: 'Steamed milk', amount: '180 ml', ratio: 64, color: C.milk, sound: 'pour', note: 'The bulk of the drink' },
        { type: 'foam', label: 'Thin foam', amount: '1 cm', ratio: 18, color: C.foam, sound: 'froth', note: 'Only a thin layer on top' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.espresso, sound: 'blip', note: 'The classic canvas for latte art' },
      ],
      method: 'One shot of espresso drowned in steamed milk with just a thin skin of foam. Mild, creamy, and the home of latte art.',
      addons: ['cocoa', 'cinnamon', 'vanilla', 'hazelnut', 'caramel', 'protein', 'decaf', 'extrashot'] },
    { id: 'cafeaulait', name: 'Caf\u00e9 au Lait', temp: 'hot', vessel: 'mug', tagline: 'Half brewed coffee, half hot milk.',
      steps: [
        { type: 'coldbrew', label: 'Brewed coffee', amount: '120 ml', ratio: 50, color: C.brewed, sound: 'pour', note: 'Drip or French press - not espresso' },
        { type: 'milk', label: 'Hot milk', amount: '120 ml', ratio: 50, color: C.milk, sound: 'pour', note: 'Scalded or steamed, poured at the same time if you are fancy' },
      ],
      method: 'The French breakfast bowl: equal parts strong brewed coffee and hot milk. Gentler than a latte because the base is filter coffee, not espresso.',
      addons: ['cinnamon', 'vanilla', 'hazelnut'] },
    { id: 'mocha', name: 'Caffè Mocha', temp: 'hot', vessel: 'mug', tagline: 'A latte that went through chocolate.',
      steps: [
        { type: 'syrup', label: 'Chocolate', amount: '30 ml', ratio: 22, color: C.choc, sound: 'syrup', note: 'Chocolate syrup or melted cocoa in first' },
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 22, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured over the chocolate and stirred' },
        { type: 'milk', label: 'Steamed milk', amount: '120 ml', ratio: 45, color: C.milk, sound: 'pour', note: 'Fills the cup' },
        { type: 'foam', label: 'Foam or cream', amount: 'a cap', ratio: 11, color: C.foam, sound: 'froth', note: 'Finished with foam or whipped cream' },
      ],
      method: 'Chocolate goes in first, espresso melts into it, then steamed milk. A cappuccino and hot chocolate combined.',
      addons: ['cream', 'cocoa', 'caramel', 'hazelnut', 'decaf', 'extrashot'] },
    { id: 'americano', name: 'Americano', temp: 'hot', vessel: 'mug', tagline: 'Espresso, lengthened with hot water.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '60 ml', ratio: 38, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot' },
        { type: 'water', label: 'Hot water', amount: '120 ml', ratio: 62, color: C.water, sound: 'pour', note: 'Hot water stretches it to coffee strength' },
      ],
      method: 'A double espresso diluted with hot water. Same caffeine as the shot, sippable like filter coffee, crema intact.',
      addons: ['cream', 'vanilla', 'decaf', 'extrashot'] },
    { id: 'redeye', name: 'Red Eye', temp: 'hot', vessel: 'mug', tagline: 'Drip coffee with a shot dropped in.',
      steps: [
        { type: 'coldbrew', label: 'Drip coffee', amount: '180 ml', ratio: 75, color: C.brewed, sound: 'pour', note: 'A full cup of filter coffee' },
        { type: 'espresso', label: 'Espresso shot', amount: '30 ml', ratio: 25, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'One shot dropped straight in - a black eye adds two' },
      ],
      method: 'A cup of filter coffee fortified with a shot of espresso. Named after the overnight flights it was built to survive.',
      addons: ['cream', 'extrashot'] },
    { id: 'irishcoffee', name: 'Irish Coffee', temp: 'hot', vessel: 'mug', tagline: 'Coffee, whiskey, sugar, and a cream collar.',
      steps: [
        { type: 'sugar', label: 'Brown sugar', amount: '2 tsp', ratio: 6, color: C.sugar, sound: 'dust', note: 'Dissolved in the hot glass first' },
        { type: 'spirit', label: 'Irish whiskey', amount: '40 ml', ratio: 20, color: C.whiskey, sound: 'pour', note: 'A generous measure' },
        { type: 'coldbrew', label: 'Hot coffee', amount: '120 ml', ratio: 58, color: C.brewed, sound: 'pour', note: 'Strong, hot brewed coffee fills the glass' },
        { type: 'foam', label: 'Cold cream float', amount: '2 cm', ratio: 16, color: '#f6f2e6', sound: 'froth', note: 'Poured over the back of a spoon so it floats' },
      ],
      method: 'Sugar and Irish whiskey in a warmed glass, topped with strong hot coffee, then cold cream floated on top. You drink the coffee through the cream - never stir it in.',
      addons: ['cocoa'] },
    { id: 'icedamericano', name: 'Iced Americano', temp: 'cold', vessel: 'highball', tagline: 'Cold, sharp, and straight to the point.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '6 cubes', ratio: 20, color: C.ice, sound: 'clink', note: 'A full glass of ice' },
        { type: 'water', label: 'Cold water', amount: '120 ml', ratio: 45, color: C.water, sound: 'pour', note: 'Cold water over the ice' },
        { type: 'espresso', label: 'Espresso', amount: '60 ml', ratio: 35, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'The shot floats on top, then marbles down' },
      ],
      method: 'Ice and cold water first, espresso poured over the top so it marbles through the glass. Bold and refreshing.',
      addons: ['vanilla', 'caramel', 'decaf', 'extrashot'] },
    { id: 'icedlatte', name: 'Iced Latte', temp: 'cold', vessel: 'highball', tagline: 'Milk over ice, espresso through the middle.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '6 cubes', ratio: 18, color: C.ice, sound: 'clink', note: 'Fill the glass with ice' },
        { type: 'milk', label: 'Cold milk', amount: '150 ml', ratio: 55, color: C.milk, sound: 'pour', note: 'Cold milk straight over the ice' },
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 27, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured last so it layers on top' },
      ],
      method: 'Ice, cold milk, then the shot poured slowly so it floats in a dark layer before you stir. The most photogenic pour in coffee.',
      addons: ['vanilla', 'hazelnut', 'caramel', 'cream', 'decaf', 'extrashot'] },
    { id: 'coldbrew', name: 'Cold Brew', temp: 'cold', vessel: 'highball', tagline: 'Steeped for 18 hours, never heated.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '4 cubes', ratio: 18, color: C.ice, sound: 'clink', note: 'A few cubes, not a full glass' },
        { type: 'coldbrew', label: 'Cold brew', amount: '200 ml', ratio: 82, color: C.coldbrew, sound: 'pour', note: 'Coarse grounds steeped in cold water for 12-24 hours' },
      ],
      method: 'Coarse coffee steeped in cold water for up to a day, then filtered. Smoother, sweeter, and more caffeinated than iced espresso drinks.',
      addons: ['cream', 'vanilla', 'caramel'] },
    { id: 'nitrocoldbrew', name: 'Nitro Cold Brew', temp: 'cold', vessel: 'highball', tagline: 'Cold brew on nitro - it pours like a stout.',
      steps: [
        { type: 'fizz', label: 'Nitro cold brew', amount: '200 ml', ratio: 80, color: C.coldbrew, sound: 'fizz', note: 'Charged with nitrogen and poured under pressure' },
        { type: 'foam', label: 'The cascade head', amount: '', ratio: 20, color: '#caa872', sound: 'froth', note: 'Tiny bubbles settle into a Guinness-style cap' },
      ],
      method: 'Cold brew infused with nitrogen and served from a tap, like draught beer. The micro-bubbles make it taste creamy and sweet with no milk, no sugar, and no ice.',
      addons: ['cream', 'vanilla', 'caramel'] },
    { id: 'frappe', name: 'Frappé', temp: 'cold', vessel: 'highball', tagline: 'Shaken instant coffee with a foam crown.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '4 cubes', ratio: 16, color: C.ice, sound: 'clink', note: 'Ice in the shaker' },
        { type: 'shake', label: 'Coffee + sugar, shaken', amount: '2 tsp', ratio: 0, color: C.frappe, sound: 'shake', note: 'Instant coffee, sugar and a splash of water, shaken hard' },
        { type: 'frappefoam', label: 'Shaken foam', amount: '', ratio: 30, color: '#c8a878', sound: 'froth', note: 'The shake builds a thick, stable foam' },
        { type: 'water', label: 'Cold water', amount: '150 ml', ratio: 54, color: C.water, sound: 'pour', note: 'Topped up with cold water' },
      ],
      method: 'A Greek invention: instant coffee and sugar shaken with ice until it foams, then topped with cold water. The foam is the whole point.',
      addons: ['cream', 'vanilla', 'caramel', 'icecream'] },
    { id: 'dalgona', name: 'Dalgona Coffee', temp: 'cold', vessel: 'highball', tagline: 'Whipped coffee floating on cold milk.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '4 cubes', ratio: 18, color: C.ice, sound: 'clink', note: 'A few cubes in a tall glass' },
        { type: 'milk', label: 'Cold milk', amount: '150 ml', ratio: 55, color: C.milk, sound: 'pour', note: 'Over the ice' },
        { type: 'scoop', label: 'Whipped coffee', amount: '2 tbsp each', ratio: 27, color: '#c89a5e', sound: 'thud', note: 'Instant coffee, sugar and hot water whipped 400 times' },
      ],
      method: 'Equal parts instant coffee, sugar and hot water, whipped by hand into a stiff caramel foam and spooned over iced milk. The lockdown legend of 2020.',
      addons: ['cocoa', 'cinnamon', 'vanilla'] },
    { id: 'shakerato', name: 'Caff\u00e8 Shakerato', temp: 'cold', vessel: 'martini', tagline: 'Espresso shaken over ice until it froths.',
      steps: [
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'A cocktail shaker, not a barista pitcher' },
        { type: 'espresso', label: 'Espresso', amount: '60 ml', ratio: 68, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot, still hot, straight into the tin' },
        { type: 'syrup', label: 'Sugar syrup', amount: '10 ml', ratio: 14, color: '#b06a28', sound: 'syrup', note: 'A little sweetness against the cold' },
        { type: 'shake', label: 'Shaken hard', amount: '15 sec', ratio: 0, color: C.espresso, sound: 'shake', note: 'Shake until the tin frosts over' },
        { type: 'strain', label: 'Strained into a coupe', amount: '', ratio: 18, color: '#6b4426', sound: 'pour', note: 'The shake builds a thick, natural crema' },
      ],
      method: 'The Italian answer to iced coffee: a fresh double espresso shaken hard with ice and a little sugar, strained into a chilled coupe. No milk - the froth is all coffee.',
      addons: ['vanilla'] },
    { id: 'affogato', name: 'Affogato', temp: 'cold', vessel: 'glass-small', tagline: 'Ice cream drowned in espresso.',
      steps: [
        { type: 'scoop', label: 'Vanilla ice cream', amount: '1 scoop', ratio: 55, color: '#f3e9d2', sound: 'thud', note: 'A cold scoop in a chilled glass' },
        { type: 'espresso', label: 'Hot espresso', amount: '30 ml', ratio: 45, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured over hot - it "drowns" the scoop' },
      ],
      method: 'Affogato means "drowned". A scoop of vanilla ice cream with a shot of hot espresso poured over it. Dessert and coffee in one.',
      addons: ['cocoa', 'caramel', 'hazelnut', 'extrashot'] },
    { id: 'vietnamese', name: 'Vietnamese Iced Coffee', temp: 'cold', vessel: 'glass-small', tagline: 'Condensed milk under slow-dripped robusta.',
      steps: [
        { type: 'syrup', label: 'Condensed milk', amount: '30 ml', ratio: 22, color: C.condensed, sound: 'syrup', note: 'Sweetened condensed milk in the glass first' },
        { type: 'coldbrew', label: 'Phin-dripped coffee', amount: '90 ml', ratio: 48, color: C.brewed, sound: 'pour', note: 'Dark robusta dripping slowly through a metal phin' },
        { type: 'ice', label: 'Ice', amount: 'fill the glass', ratio: 30, color: C.ice, sound: 'clink', note: 'Stirred over ice - ca phe sua da' },
      ],
      method: 'A layer of sweetened condensed milk, then robusta coffee dripped through a small metal phin filter, stirred and poured over ice. Sweet, strong, and thick.',
      addons: ['cream'] },
    { id: 'turkish', name: 'Turkish Coffee', temp: 'hot', vessel: 'demitasse', tagline: 'Cooked in a cezve, grounds and all.',
      steps: [
        { type: 'sugar', label: 'Sugar', amount: '1 tsp', ratio: 8, color: C.sugar, sound: 'dust', note: 'Added at the start - you cannot sweeten it later' },
        { type: 'water', label: 'Cold water', amount: '60 ml', ratio: 32, color: C.water, sound: 'pour', note: 'Into the cezve, one small cup per serving' },
        { type: 'coldbrew', label: 'Powder-fine coffee', amount: '2 tsp', ratio: 45, color: C.espresso, sound: 'pour', note: 'Ground finer than espresso, stirred in cold' },
        { type: 'foam', label: 'The kaimaki', amount: '', ratio: 15, color: C.crema, sound: 'froth', note: 'Heated slowly until the foam rises - never boiled' },
      ],
      method: 'Ultra-fine coffee simmered with water and sugar in a small copper cezve until the foam rises, then poured unfiltered. Let the grounds settle, sip slowly, and never drink the last mouthful.',
      addons: [] },
    { id: 'cafebombon', name: 'Caf\u00e9 Bomb\u00f3n', temp: 'hot', vessel: 'glass-small', tagline: 'Espresso over condensed milk, in perfect stripes.',
      steps: [
        { type: 'syrup', label: 'Condensed milk', amount: '30 ml', ratio: 50, color: C.condensed, sound: 'syrup', note: 'Poured first so it settles at the bottom' },
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 50, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured slowly so the layers stay separate' },
      ],
      method: 'Valencia in a glass: equal parts condensed milk and espresso, poured so they sit in two clean stripes. Stir it or drink through the layers - your call.',
      addons: ['cocoa'] },
  ],
  cocktails: [
    { id: 'martini', name: 'Dry Martini', spirit: 'gin', vessel: 'martini', tagline: 'Gin, a whisper of vermouth, ice-cold.',
      steps: [
        { type: 'ice', label: 'Ice in the mixing glass', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Chilled and stirred, never shaken (sorry, Bond)' },
        { type: 'spirit', label: 'Gin', amount: '60 ml', ratio: 78, color: C.gin, sound: 'pour', note: 'London dry, stirred over ice' },
        { type: 'spirit', label: 'Dry vermouth', amount: '10 ml', ratio: 14, color: C.vermouth, sound: 'pour', note: 'Just a whisper - the drier, the less vermouth' },
        { type: 'stir', label: 'Stirred & strained', amount: '30 sec', ratio: 0, color: C.gin, sound: 'stir', note: 'Stirred silky, strained into a frozen coupe' },
        { type: 'garnish-olive', label: 'Olive or lemon twist', amount: '', ratio: 8, color: '#7a8a3a', sound: 'blip', note: 'The garnish is the final word' },
      ],
      method: 'Gin and dry vermouth stirred with ice until freezing, strained into a chilled martini glass, garnished with an olive or a twist of lemon.',
      addons: [] },
    { id: 'mule', name: 'Moscow Mule', spirit: 'vodka', vessel: 'copper', tagline: 'Vodka, ginger beer, lime - in copper.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the mug', ratio: 22, color: C.ice, sound: 'clink', note: 'The copper mug keeps it arctic' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 24, color: C.vodka, sound: 'pour', note: 'Over the ice' },
        { type: 'spirit', label: 'Lime juice', amount: '15 ml', ratio: 8, color: C.lime, sound: 'pour', note: 'Half a lime, squeezed fresh' },
        { type: 'fizz', label: 'Ginger beer', amount: '120 ml', ratio: 46, color: C.gingerbeer, sound: 'fizz', note: 'Spicy ginger beer to the top' },
        { type: 'garnish-lime', label: 'Lime wheel & mint', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'A wheel of lime and a slap of mint' },
      ],
      method: 'Vodka and fresh lime over ice in a copper mug, topped with spicy ginger beer. The copper is not decoration - it keeps the drink colder.',
      addons: [] },
    { id: 'margarita', name: 'Margarita', spirit: 'tequila', vessel: 'margarita', tagline: 'Tequila, lime, triple sec, salt rim.',
      steps: [
        { type: 'rim', label: 'Salt rim', amount: '', ratio: 0, color: '#f0ead8', sound: 'dust', note: 'Lime around the rim, dipped in salt' },
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Everything goes into the shaker' },
        { type: 'spirit', label: 'Tequila blanco', amount: '50 ml', ratio: 45, color: C.tequila, sound: 'pour', note: '100% agave, always' },
        { type: 'spirit', label: 'Triple sec', amount: '20 ml', ratio: 18, color: C.triplesec, sound: 'pour', note: 'Orange liqueur for sweetness' },
        { type: 'spirit', label: 'Lime juice', amount: '25 ml', ratio: 22, color: C.lime, sound: 'pour', note: 'Fresh lime, no exceptions' },
        { type: 'shake', label: 'Shaken hard', amount: '15 sec', ratio: 0, color: C.tequila, sound: 'shake', note: 'Shake until the tin frosts' },
        { type: 'strain', label: 'Strained over ice', amount: '', ratio: 15, color: '#e4e0c0', sound: 'pour', note: 'Fine-strained into the salted glass' },
        { type: 'garnish-lime', label: 'Lime wheel', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'On the rim' },
      ],
      method: 'Tequila, triple sec and fresh lime shaken hard with ice, strained into a salt-rimmed glass. Sour, cold, and balanced.',
      addons: [] },
    { id: 'screwdriver', name: 'Screwdriver', spirit: 'vodka', vessel: 'highball', tagline: 'Vodka and orange juice. That is it.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A highball full of ice' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 28, color: C.vodka, sound: 'pour', note: 'Over the ice' },
        { type: 'juice', label: 'Orange juice', amount: '120 ml', ratio: 52, color: C.oj, sound: 'pour', note: 'Fresh squeezed if you can' },
        { type: 'garnish-orange', label: 'Orange slice', amount: '', ratio: 0, color: C.oj, sound: 'blip', note: 'A slice on the rim' },
      ],
      method: 'Two ingredients over ice: vodka and orange juice, stirred once. Named by oil workers who stirred it with screwdrivers.',
      addons: [] },
    { id: 'jagerbomb', name: 'Jägerbomb', spirit: 'other', vessel: 'bomb', tagline: 'A shot of Jäger dropped into energy drink.',
      steps: [
        { type: 'fizz', label: 'Energy drink', amount: '150 ml', ratio: 70, color: C.energy, sound: 'fizz', note: 'Half a can, ice cold, in the glass' },
        { type: 'shotglass', label: 'Jägermeister shot', amount: '30 ml', ratio: 30, color: C.jager, sound: 'pour', note: 'A full shot, poured separately' },
        { type: 'drop', label: 'The drop', amount: '', ratio: 0, color: C.jager, sound: 'splash', note: 'Drop the shot in and drink immediately' },
      ],
      method: 'A shot of ice-cold Jägermeister dropped into a glass of energy drink. The drop mixes it at the table. Built for toasts, not sipping.',
      addons: [] },
    { id: 'mojito', name: 'Mojito', spirit: 'rum', vessel: 'highball', tagline: 'Mint, lime, rum, soda - muddled fresh.',
      steps: [
        { type: 'garnish-mint', label: 'Mint leaves', amount: '8 leaves', ratio: 6, color: C.mint, sound: 'blip', note: 'Slapped, not shredded' },
        { type: 'sugar', label: 'Sugar + lime', amount: '2 tsp + half a lime', ratio: 8, color: C.sugar, sound: 'dust', note: 'Muddled gently with the mint' },
        { type: 'ice', label: 'Crushed ice', amount: 'fill', ratio: 24, color: C.ice, sound: 'clink', note: 'Crushed, not cubed' },
        { type: 'spirit', label: 'White rum', amount: '50 ml', ratio: 30, color: C.rum, sound: 'pour', note: 'Over the ice' },
        { type: 'fizz', label: 'Soda water', amount: 'top up', ratio: 32, color: C.soda, sound: 'fizz', note: 'Topped with soda and lifted with a spoon' },
        { type: 'garnish-mint', label: 'Mint sprig', amount: '', ratio: 0, color: C.mint, sound: 'blip', note: 'A big sprig so you smell it first' },
      ],
      method: 'Mint and lime muddled with sugar, white rum over crushed ice, topped with soda. Cuba in a glass.',
      addons: [] },
    { id: 'oldfashioned', name: 'Old Fashioned', spirit: 'whiskey', vessel: 'rocks', tagline: 'Whiskey, sugar, bitters. The original cocktail.',
      steps: [
        { type: 'sugar', label: 'Sugar cube + bitters', amount: '1 cube, 2 dashes', ratio: 6, color: C.sugar, sound: 'dust', note: 'Bitters soaked into the cube, muddled' },
        { type: 'iceblock', label: 'One big ice block', amount: '', ratio: 26, color: C.ice, sound: 'clink', note: 'One large cube - it melts slow' },
        { type: 'spirit', label: 'Bourbon or rye', amount: '60 ml', ratio: 60, color: C.whiskey, sound: 'pour', note: 'Poured over the ice, stirred briefly' },
        { type: 'garnish-orange', label: 'Orange peel', amount: '', ratio: 8, color: '#d8842a', sound: 'blip', note: 'Expressed over the glass, oils and all' },
      ],
      method: 'A sugar cube soaked in bitters, muddled, one large ice block, and good whiskey stirred over it. The template every cocktail descends from.',
      addons: [] },
    { id: 'gintonic', name: 'Gin & Tonic', spirit: 'gin', vessel: 'highball', tagline: 'Two ingredients, endless ritual.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 22, color: C.ice, sound: 'clink', note: 'Lots of ice - it melts slower' },
        { type: 'spirit', label: 'Gin', amount: '50 ml', ratio: 26, color: C.gin, sound: 'pour', note: 'London dry over the ice' },
        { type: 'fizz', label: 'Tonic water', amount: '150 ml', ratio: 52, color: C.tonic, sound: 'fizz', note: 'Poured gently to keep the fizz' },
        { type: 'garnish-lime', label: 'Lime wedge', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'Squeezed and dropped in' },
      ],
      method: 'Gin over a glass packed with ice, topped with tonic poured down the side to keep the bubbles, finished with lime.',
      addons: [] },
    { id: 'negroni', name: 'Negroni', spirit: 'gin', vessel: 'rocks', tagline: 'Equal parts gin, Campari, sweet vermouth.',
      steps: [
        { type: 'iceblock', label: 'One big ice block', amount: '', ratio: 24, color: C.ice, sound: 'clink', note: 'A single large cube in a heavy rocks glass' },
        { type: 'spirit', label: 'Gin', amount: '30 ml', ratio: 26, color: C.gin, sound: 'pour', note: 'London dry' },
        { type: 'spirit', label: 'Campari', amount: '30 ml', ratio: 26, color: C.campari, sound: 'pour', note: 'Bitter, red, and unmistakable' },
        { type: 'spirit', label: 'Sweet vermouth', amount: '30 ml', ratio: 24, color: C.sweetvermouth, sound: 'pour', note: 'Rosso - the glue between gin and Campari' },
        { type: 'stir', label: 'Stirred', amount: '20 sec', ratio: 0, color: C.campari, sound: 'stir', note: 'Stirred right in the glass' },
        { type: 'garnish-orange', label: 'Orange peel', amount: '', ratio: 0, color: '#d8842a', sound: 'blip', note: 'Expressed over the top' },
      ],
      method: 'Three equal parts stirred over ice: gin, Campari, sweet vermouth. Bitter, sweet, and herbal in perfect balance - invented in Florence in 1919 when Count Negroni asked for a stronger Americano.',
      addons: [] },
    { id: 'manhattan', name: 'Manhattan', spirit: 'whiskey', vessel: 'martini', tagline: 'Rye, sweet vermouth, bitters - stirred, up.',
      steps: [
        { type: 'ice', label: 'Ice in the mixing glass', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Always stirred, never shaken' },
        { type: 'spirit', label: 'Rye whiskey', amount: '60 ml', ratio: 65, color: C.whiskey, sound: 'pour', note: 'Rye for spice, bourbon for a sweeter take' },
        { type: 'spirit', label: 'Sweet vermouth', amount: '30 ml', ratio: 32, color: C.sweetvermouth, sound: 'pour', note: 'The 2:1 ratio is the classic' },
        { type: 'syrup', label: 'Angostura bitters', amount: '2 dashes', ratio: 3, color: C.bitters, sound: 'syrup', note: 'Two dashes, no more' },
        { type: 'stir', label: 'Stirred & strained', amount: '30 sec', ratio: 0, color: C.whiskey, sound: 'stir', note: 'Stirred silky, strained into a chilled coupe' },
        { type: 'garnish-cherry', label: 'Brandied cherry', amount: '', ratio: 0, color: '#a81c2a', sound: 'blip', note: 'One good cherry, not three neon ones' },
      ],
      method: 'Rye and sweet vermouth stirred with ice and bitters, strained into a chilled glass with a cherry. The sophisticated ancestor of every whiskey cocktail.',
      addons: [] },
    { id: 'daiquiri', name: 'Daiquiri', spirit: 'rum', vessel: 'martini', tagline: 'Rum, lime, sugar - the sour at its purest.',
      steps: [
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Everything goes into the tin' },
        { type: 'spirit', label: 'White rum', amount: '60 ml', ratio: 45, color: C.rum, sound: 'pour', note: 'A clean, light rum' },
        { type: 'spirit', label: 'Lime juice', amount: '25 ml', ratio: 20, color: C.lime, sound: 'pour', note: 'Fresh squeezed, always' },
        { type: 'syrup', label: 'Sugar syrup', amount: '15 ml', ratio: 15, color: C.sugar, sound: 'syrup', note: 'Just enough to take the edge off' },
        { type: 'shake', label: 'Shaken hard', amount: '15 sec', ratio: 0, color: C.rum, sound: 'shake', note: 'Shake until the tin frosts' },
        { type: 'strain', label: 'Strained, straight up', amount: '', ratio: 20, color: '#e4e0c0', sound: 'pour', note: 'Served up in a chilled coupe - no ice, no blender' },
      ],
      method: 'White rum, fresh lime and sugar, shaken hard and served straight up. Nothing to hide behind - the truest test of a rum and a bartender. Named for a Cuban beach, not a slushy machine.',
      addons: [] },
    { id: 'cosmopolitan', name: 'Cosmopolitan', spirit: 'vodka', vessel: 'martini', tagline: 'Vodka, cranberry, lime - pink and sharp.',
      steps: [
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Everything into the tin' },
        { type: 'spirit', label: 'Vodka', amount: '40 ml', ratio: 44, color: C.vodka, sound: 'pour', note: 'Citron vodka is the classic call' },
        { type: 'juice', label: 'Cranberry juice', amount: '30 ml', ratio: 26, color: C.cranberry, sound: 'pour', note: 'Just enough for the blush' },
        { type: 'spirit', label: 'Triple sec', amount: '15 ml', ratio: 16, color: C.triplesec, sound: 'pour', note: 'Orange liqueur' },
        { type: 'spirit', label: 'Lime juice', amount: '15 ml', ratio: 14, color: C.lime, sound: 'pour', note: 'Fresh lime' },
        { type: 'shake', label: 'Shaken hard', amount: '15 sec', ratio: 0, color: C.cranberry, sound: 'shake', note: 'Until ice cold' },
        { type: 'garnish-orange', label: 'Orange twist', amount: '', ratio: 0, color: '#d8842a', sound: 'blip', note: 'Flamed over the glass if you are showing off' },
      ],
      method: 'Vodka, triple sec, cranberry and lime shaken hard and served up. A proper 1980s sour long before a certain TV show made it famous.',
      addons: [] },
    { id: 'whiskeysour', name: 'Whiskey Sour', spirit: 'whiskey', vessel: 'rocks', tagline: 'Whiskey, lemon, sugar, and a silky foam cap.',
      steps: [
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Dry-shake first if using egg white' },
        { type: 'spirit', label: 'Bourbon', amount: '60 ml', ratio: 46, color: C.whiskey, sound: 'pour', note: 'Bourbon is the classic base' },
        { type: 'spirit', label: 'Lemon juice', amount: '30 ml', ratio: 22, color: C.lemon, sound: 'pour', note: 'Fresh lemon, never bottled' },
        { type: 'syrup', label: 'Sugar syrup', amount: '15 ml', ratio: 12, color: C.sugar, sound: 'syrup', note: 'Balance the sour' },
        { type: 'foam', label: 'Egg white foam', amount: '1 white', ratio: 20, color: '#f6f2e6', sound: 'froth', note: 'Dry-shaken for the silky cap - aquafaba works too' },
        { type: 'shake', label: 'Shaken twice', amount: '20 sec', ratio: 0, color: C.whiskey, sound: 'shake', note: 'Once without ice, once with' },
        { type: 'garnish-cherry', label: 'Cherry & orange', amount: '', ratio: 0, color: '#a81c2a', sound: 'blip', note: 'On a pick across the glass' },
      ],
      method: 'Bourbon, fresh lemon and sugar shaken with egg white for a silky foam cap, served over ice. The template of the whole sour family.',
      addons: [] },
    { id: 'espressomartini', name: 'Espresso Martini', spirit: 'vodka', vessel: 'martini', tagline: 'Vodka, coffee liqueur, fresh espresso - shaken awake.',
      steps: [
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Everything into the tin' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 40, color: C.vodka, sound: 'pour', note: 'The neutral base' },
        { type: 'spirit', label: 'Coffee liqueur', amount: '25 ml', ratio: 20, color: C.coffeeliq, sound: 'pour', note: 'Sweet and dark' },
        { type: 'espresso', label: 'Fresh espresso', amount: '30 ml', ratio: 25, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Must be fresh - the crema depends on it' },
        { type: 'shake', label: 'Shaken very hard', amount: '20 sec', ratio: 0, color: C.espresso, sound: 'shake', note: 'The violent shake is what builds the foam' },
        { type: 'foam', label: 'The crema cap', amount: '', ratio: 15, color: C.crema, sound: 'froth', note: 'A thick tan foam rises as it settles' },
      ],
      method: 'Vodka, coffee liqueur and a fresh shot of espresso shaken hard with ice, strained into a chilled glass. The shake whips the coffee oils into the signature crema. Invented in 1980s London for a customer who wanted to be woken up.',
      addons: [] },
    { id: 'pinacolada', name: 'Pi\u00f1a Colada', spirit: 'rum', vessel: 'hurricane', tagline: 'Rum, coconut, pineapple - blended sunshine.',
      steps: [
        { type: 'ice', label: 'Crushed ice', amount: 'a cup', ratio: 0, color: C.ice, sound: 'clink', note: 'Into the blender' },
        { type: 'spirit', label: 'White rum', amount: '60 ml', ratio: 28, color: C.rum, sound: 'pour', note: 'Puerto Rican rum is the original' },
        { type: 'spirit', label: 'Coconut cream', amount: '50 ml', ratio: 30, color: C.coconut, sound: 'pour', note: 'Cream of coconut - thick and sweet' },
        { type: 'juice', label: 'Pineapple juice', amount: '90 ml', ratio: 42, color: C.pineapple, sound: 'pour', note: 'Fresh pressed if you can' },
        { type: 'shake', label: 'Blended smooth', amount: '20 sec', ratio: 0, color: C.coconut, sound: 'shake', note: 'Blended until it pours like a milkshake' },
        { type: 'garnish-cherry', label: 'Pineapple & cherry', amount: '', ratio: 0, color: C.pineapple, sound: 'blip', note: 'A wedge on the rim, a cherry on top' },
      ],
      method: 'Rum, coconut cream and pineapple juice blended with crushed ice until smooth. The national drink of Puerto Rico since 1978 - the name means "strained pineapple".',
      addons: [] },
    { id: 'maitai', name: 'Mai Tai', spirit: 'rum', vessel: 'rocks', tagline: 'Two rums, lime, orgeat - tiki royalty.',
      steps: [
        { type: 'ice', label: 'Crushed ice', amount: 'fill', ratio: 24, color: C.ice, sound: 'clink', note: 'A mountain of crushed ice' },
        { type: 'spirit', label: 'Light rum', amount: '30 ml', ratio: 24, color: C.rum, sound: 'pour', note: 'The clean half of the blend' },
        { type: 'spirit', label: 'Lime juice', amount: '20 ml', ratio: 14, color: C.lime, sound: 'pour', note: 'Fresh squeezed' },
        { type: 'spirit', label: 'Orange curacao', amount: '15 ml', ratio: 12, color: C.triplesec, sound: 'pour', note: 'Dry orange, not sweet blue' },
        { type: 'syrup', label: 'Orgeat', amount: '15 ml', ratio: 10, color: C.condensed, sound: 'syrup', note: 'Almond syrup - the soul of tiki' },
        { type: 'shake', label: 'Shaken briefly', amount: '10 sec', ratio: 0, color: C.rum, sound: 'shake', note: 'Just enough to chill and mix' },
        { type: 'spirit', label: 'Dark rum float', amount: '30 ml', ratio: 16, color: C.darkrum, sound: 'pour', note: 'Floated on top like a sunset' },
        { type: 'garnish-mint', label: 'Mint & lime shell', amount: '', ratio: 0, color: C.mint, sound: 'blip', note: 'The spent lime half becomes the garnish' },
      ],
      method: 'Trader Vic invented it in 1944: light and dark rum, lime, orange curacao and orgeat shaken and poured over crushed ice. "Maitai" is Tahitian for "the best".',
      addons: [] },
    { id: 'aperolspritz', name: 'Aperol Spritz', spirit: 'other', vessel: 'wine', tagline: 'Aperol, prosecco, soda - the Venetian hour.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A big wine glass packed with ice' },
        { type: 'fizz', label: 'Prosecco', amount: '90 ml', ratio: 42, color: C.prosecco, sound: 'fizz', note: 'In first, so the Aperol does not sink straight to the bottom' },
        { type: 'spirit', label: 'Aperol', amount: '60 ml', ratio: 30, color: C.aperol, sound: 'pour', note: 'Bitter orange and rhubarb' },
        { type: 'fizz', label: 'Soda water', amount: '30 ml', ratio: 8, color: C.soda, sound: 'fizz', note: 'A splash on top' },
        { type: 'garnish-orange', label: 'Orange slice', amount: '', ratio: 0, color: '#e8963a', sound: 'blip', note: 'A thick slice, right in the glass' },
      ],
      method: 'The 3-2-1: three parts prosecco, two parts Aperol, one part soda, over ice in a big wine glass. The aperitivo hour, exported from Venice to everywhere.',
      addons: [] },
    { id: 'bloodymary', name: 'Bloody Mary', spirit: 'vodka', vessel: 'highball', tagline: 'Vodka, tomato, spice - the brunch cure.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A tall glass, well chilled' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 26, color: C.vodka, sound: 'pour', note: 'The quiet base' },
        { type: 'juice', label: 'Tomato juice', amount: '120 ml', ratio: 46, color: C.tomato, sound: 'pour', note: 'The body of the drink' },
        { type: 'spirit', label: 'Lemon juice', amount: '15 ml', ratio: 6, color: C.lemon, sound: 'pour', note: 'Brightness against the tomato' },
        { type: 'syrup', label: 'Worcestershire & Tabasco', amount: '3 dashes each', ratio: 2, color: C.bitters, sound: 'syrup', note: 'Plus celery salt and black pepper' },
        { type: 'stir', label: 'Rolled, not shaken', amount: '', ratio: 0, color: C.tomato, sound: 'stir', note: 'Rolling keeps the tomato silky' },
        { type: 'garnish-lime', label: 'Lime & celery', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'The classic celery stalk doubles as a stirrer' },
      ],
      method: 'Vodka and tomato juice over ice with lemon, Worcestershire, Tabasco, celery salt and pepper, gently rolled. The one cocktail nobody questions before noon.',
      addons: [] },
    { id: 'tequilasunrise', name: 'Tequila Sunrise', spirit: 'tequila', vessel: 'highball', tagline: 'Tequila, orange, and a grenadine sunrise.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A tall glass of ice' },
        { type: 'spirit', label: 'Tequila blanco', amount: '50 ml', ratio: 28, color: C.tequila, sound: 'pour', note: 'Over the ice' },
        { type: 'juice', label: 'Orange juice', amount: '120 ml', ratio: 44, color: C.oj, sound: 'pour', note: 'To the top' },
        { type: 'syrup', label: 'Grenadine', amount: '20 ml', ratio: 8, color: C.grenadine, sound: 'syrup', note: 'Poured down the side - it sinks, then rises like a sunrise' },
        { type: 'garnish-orange', label: 'Orange slice & cherry', amount: '', ratio: 0, color: C.oj, sound: 'blip', note: 'On the rim' },
      ],
      method: 'Tequila and orange juice over ice, with grenadine poured in last so it sinks and bleeds upward in red streaks. Do not stir - the gradient is the whole point.',
      addons: [] },
    { id: 'sangria', name: 'Sangria', spirit: 'other', vessel: 'wine', tagline: 'Wine, fruit, brandy - the Spanish pitcher.',
      steps: [
        { type: 'garnish-orange', label: 'Orange & apple', amount: '1 each, chopped', ratio: 10, color: C.oj, sound: 'blip', note: 'Fruit goes in the pitcher first' },
        { type: 'spirit', label: 'Red wine', amount: '150 ml', ratio: 52, color: C.redwine, sound: 'pour', note: 'A dry, fruity Spanish red' },
        { type: 'spirit', label: 'Brandy', amount: '30 ml', ratio: 12, color: C.whiskey, sound: 'pour', note: 'The quiet kick' },
        { type: 'juice', label: 'Orange juice', amount: '60 ml', ratio: 18, color: C.oj, sound: 'pour', note: 'Fresh squeezed' },
        { type: 'syrup', label: 'A little sugar', amount: '1 tbsp', ratio: 8, color: C.sugar, sound: 'syrup', note: 'To taste' },
        { type: 'stir', label: 'Stirred & rested', amount: '2+ hours', ratio: 0, color: C.redwine, sound: 'stir', note: 'The fruit needs time to soak' },
      ],
      method: 'Chopped fruit soaked with red wine, brandy, orange juice and a little sugar, rested for hours so the flavors marry. Named for sangre - blood - after its deep red color.',
      addons: [] },
    { id: 'caipirinha', name: 'Caipirinha', spirit: 'other', vessel: 'rocks', tagline: 'Cacha\u00e7a, lime, sugar - Brazil in a glass.',
      steps: [
        { type: 'garnish-lime', label: 'Lime wedges', amount: 'half a lime', ratio: 10, color: C.lime, sound: 'blip', note: 'Cut into wedges, straight in the glass' },
        { type: 'sugar', label: 'Sugar', amount: '2 tsp', ratio: 8, color: C.sugar, sound: 'dust', note: 'Muddled hard with the lime to pull the oils out' },
        { type: 'ice', label: 'Crushed ice', amount: 'fill', ratio: 24, color: C.ice, sound: 'clink', note: 'Piled high' },
        { type: 'spirit', label: 'Cacha\u00e7a', amount: '60 ml', ratio: 58, color: C.rum, sound: 'pour', note: 'Brazilian sugarcane spirit - funkier than rum' },
        { type: 'stir', label: 'Stirred', amount: '', ratio: 0, color: C.rum, sound: 'stir', note: 'Lift the lime through the drink' },
      ],
      method: 'Lime wedges muddled with sugar in the glass, crushed ice, and cachaca stirred through. The national cocktail of Brazil.',
      addons: [] },
    { id: 'tomcollins', name: 'Tom Collins', spirit: 'gin', vessel: 'highball', tagline: 'Gin, lemon, sugar, soda - the original tall drink.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A Collins glass, packed' },
        { type: 'spirit', label: 'Gin', amount: '50 ml', ratio: 30, color: C.gin, sound: 'pour', note: 'Old Tom gin is the original call' },
        { type: 'spirit', label: 'Lemon juice', amount: '25 ml', ratio: 14, color: C.lemon, sound: 'pour', note: 'Fresh squeezed' },
        { type: 'syrup', label: 'Sugar syrup', amount: '15 ml', ratio: 8, color: C.sugar, sound: 'syrup', note: 'Just a touch' },
        { type: 'fizz', label: 'Soda water', amount: '100 ml', ratio: 28, color: C.soda, sound: 'fizz', note: 'Topped gently to keep the bubbles' },
        { type: 'garnish-orange', label: 'Lemon wheel & cherry', amount: '', ratio: 0, color: C.lemon, sound: 'blip', note: 'The classic flag garnish' },
      ],
      method: 'Gin, lemon and sugar over ice, topped with soda. A gin sour made tall - first written down in 1876 and still the blueprint for every long drink after it.',
      addons: [] },
    { id: 'darknstormy', name: "Dark 'n' Stormy", spirit: 'rum', vessel: 'highball', tagline: 'Dark rum floated over stormy ginger beer.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 22, color: C.ice, sound: 'clink', note: 'A tall glass of ice' },
        { type: 'spirit', label: 'Lime juice', amount: '10 ml', ratio: 6, color: C.lime, sound: 'pour', note: 'A squeeze of lime' },
        { type: 'fizz', label: 'Ginger beer', amount: '100 ml', ratio: 44, color: C.gingerbeer, sound: 'fizz', note: 'The stormy part' },
        { type: 'spirit', label: 'Dark rum', amount: '60 ml', ratio: 28, color: C.darkrum, sound: 'pour', note: 'Floated last, like a storm cloud rolling in' },
        { type: 'garnish-lime', label: 'Lime wedge', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'On the rim' },
      ],
      method: 'Ginger beer over ice with a squeeze of lime, dark rum floated on top so it gathers like thunderclouds. The national drink of Bermuda.',
      addons: [] },
    { id: 'longisland', name: 'Long Island Iced Tea', spirit: 'other', vessel: 'highball', tagline: 'Five spirits, one splash of cola.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 18, color: C.ice, sound: 'clink', note: 'A tall glass, packed' },
        { type: 'spirit', label: 'Vodka', amount: '15 ml', ratio: 9, color: C.vodka, sound: 'pour', note: 'Spirit one of five' },
        { type: 'spirit', label: 'Gin', amount: '15 ml', ratio: 9, color: C.gin, sound: 'pour', note: 'Spirit two of five' },
        { type: 'spirit', label: 'White rum', amount: '15 ml', ratio: 9, color: C.rum, sound: 'pour', note: 'Spirit three of five' },
        { type: 'spirit', label: 'Tequila blanco', amount: '15 ml', ratio: 9, color: C.tequila, sound: 'pour', note: 'Spirit four of five' },
        { type: 'spirit', label: 'Triple sec', amount: '15 ml', ratio: 9, color: C.triplesec, sound: 'pour', note: 'Spirit five of five' },
        { type: 'spirit', label: 'Lemon juice', amount: '30 ml', ratio: 15, color: C.lemon, sound: 'pour', note: 'Fresh lemon to hold it together' },
        { type: 'syrup', label: 'Sugar syrup', amount: '15 ml', ratio: 7, color: C.sugar, sound: 'syrup', note: 'A little sweetness' },
        { type: 'fizz', label: 'Cola', amount: 'a splash', ratio: 15, color: C.cola, sound: 'fizz', note: 'Just a splash for color - it is not iced tea' },
        { type: 'garnish-orange', label: 'Lemon wheel', amount: '', ratio: 0, color: C.lemon, sound: 'blip', note: 'On the rim' },
      ],
      method: 'Equal shots of vodka, gin, rum, tequila and triple sec with lemon and sugar, topped with a splash of cola. Contains no tea whatsoever. Treat it with respect.',
      addons: [] },
  ],
};

export const MODE_META = {
  coffee: {
    title: 'COFFEE', accent: '#e09543',
    headline: 'What is a cappuccino, actually?',
    sub: 'Pick one. Watch it get built - every pour, in order, with sound.',
    filters: [ { id: 'all', label: 'ALL' }, { id: 'hot', label: 'HOT' }, { id: 'cold', label: 'COLD' } ],
    filterKey: 'temp', filterPrompt: 'First: hot or cold?',
    addonsTitle: 'Make it yours',
  },
  cocktails: {
    title: 'COCKTAILS', accent: '#c6f24e',
    headline: 'What goes into the glass?',
    sub: 'The right glass, the right ice, the shake, the pour, the garnish.',
    filters: [ { id: 'all', label: 'ALL' }, { id: 'gin', label: 'GIN' }, { id: 'vodka', label: 'VODKA' }, { id: 'rum', label: 'RUM' }, { id: 'tequila', label: 'TEQUILA' }, { id: 'whiskey', label: 'WHISKEY' }, { id: 'other', label: 'OTHER' } ],
    filterKey: 'spirit', filterPrompt: 'Pick your spirit',
    addonsTitle: null,
  },
};
