// Drink data. Each step: type drives the animation + sound, ratio sizes the layer.
// ratio values within a drink sum to ~100 (visual proportion of the final vessel).

export const ADDONS = {
  cocoa:     { label: 'Cocoa dust',    visual: 'sprinkle', color: '#5a3a22', sound: 'dust',   note: 'A dusting of cocoa over the foam' },
  cinnamon:  { label: 'Cinnamon',      visual: 'sprinkle', color: '#8a5a2e', sound: 'dust',   note: 'Ground cinnamon, warm and sweet' },
  cream:     { label: 'Whipped cream', visual: 'dollop',   color: '#faf5ea', sound: 'froth',  note: 'A cloud of whipped cream' },
  icecream:  { label: 'Ice cream',     visual: 'scoop',    color: '#f3e9d2', sound: 'thud',   note: 'A scoop of vanilla ice cream' },
  hazelnut:  { label: 'Hazelnut',      visual: 'syrup',    color: '#7a4a26', sound: 'syrup',  note: '10 ml hazelnut syrup' },
  vanilla:   { label: 'Vanilla',       visual: 'syrup',    color: '#e8d9a8', sound: 'syrup',  note: '10 ml vanilla syrup' },
  caramel:   { label: 'Caramel',       visual: 'syrup',    color: '#b06a28', sound: 'syrup',  note: 'A drizzle of caramel' },
  protein:   { label: 'Protein',       visual: 'dust',     color: '#d8cbb2', sound: 'dust',   note: 'A scoop of protein, blended in' },
  extrashot: { label: 'Extra shot',    visual: 'shot',     color: '#1f1208', sound: 'espresso', note: 'Another 30 ml of espresso' },
  ristretto: { label: 'Ristretto',     visual: 'tag',      color: '#1f1208', sound: 'blip',   note: 'Short pull - sweeter, more intense' },
  decaf:     { label: 'Decaf',         visual: 'tag',      color: '#8f867a', sound: 'blip',   note: 'Same ritual, no caffeine' },
};

const C = {
  espresso: '#2a1708', espressoEdge: '#4a2c12', crema: '#8a5a28',
  milk: '#d9bf9f', foam: '#f2e7d2', water: '#3d4a52', choc: '#3a1f0e',
  coldbrew: '#241408', frappe: '#6b4a2a', ice: '#cfe4ec',
  gin: '#dfe9e4', vodka: '#e8ecea', rum: '#e8e4d2', tequila: '#eee6c8', whiskey: '#c47f2a', jager: '#3a1c10',
  vermouth: '#e4dcc0', oj: '#e8963a', gingerbeer: '#d8a24a', tonic: '#dce8e4', soda: '#dce8e4',
  lime: '#9ec24a', energy: '#c8d44a', mint: '#4a7a3a', sugar: '#f0ead8', bitters: '#8a4a1a', triplesec: '#e8c88a',
};

export const DRINKS = {
  coffee: [
    { id: 'espresso', name: 'Espresso', temp: 'hot', vessel: 'demitasse', tagline: 'The pure shot. Everything starts here.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 100, color: C.espresso, edge: C.crema, sound: 'espresso', note: '18 g of fine grounds, 9 bars of pressure, 25-30 seconds' },
      ],
      method: 'Finely ground coffee is tamped into the portafilter and hot water is forced through at 9 bars. The golden crema on top is the sign of a good pull.',
      addons: ['ristretto', 'decaf', 'extrashot'] },
    { id: 'macchiato', name: 'Macchiato', temp: 'hot', vessel: 'demitasse', tagline: 'Espresso, "stained" with foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 72, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot, pulled short' },
        { type: 'foam', label: 'Milk foam', amount: 'a spoonful', ratio: 28, color: C.foam, sound: 'froth', note: 'Just a stain of foam - macchiato means "stained"' },
      ],
      method: 'A straight espresso marked with a spoonful of milk foam. The foam softens the edge without diluting the shot.',
      addons: ['cocoa', 'cinnamon', 'ristretto', 'decaf', 'extrashot'] },
    { id: 'cortado', name: 'Cortado', temp: 'hot', vessel: 'glass-small', tagline: 'Half espresso, half warm milk. No foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 50, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'The base double shot' },
        { type: 'milk', label: 'Steamed milk', amount: '30 ml', ratio: 50, color: C.milk, sound: 'pour', note: 'Steamed, not frothed - equal parts' },
      ],
      method: 'Equal parts espresso and steamed milk. The milk is warm and silky with almost no foam, cutting the acidity in half.',
      addons: ['vanilla', 'hazelnut', 'decaf', 'extrashot'] },
    { id: 'flatwhite', name: 'Flat White', temp: 'hot', vessel: 'mug', tagline: 'Velvet microfoam over a double shot.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 33, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double ristretto is the classic base' },
        { type: 'milk', label: 'Microfoam milk', amount: '130 ml', ratio: 67, color: C.milk, sound: 'pour', note: 'Steamed to a velvet texture - no dry foam' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.foam, sound: 'blip', note: 'The pour finishes with a rosetta or heart' },
      ],
      method: 'A double shot topped with microfoam - milk steamed so finely it pours like wet paint. Stronger than a latte, silkier than a cappuccino.',
      addons: ['cocoa', 'vanilla', 'hazelnut', 'caramel', 'ristretto', 'decaf', 'extrashot'] },
    { id: 'cappuccino', name: 'Cappuccino', temp: 'hot', vessel: 'mug', tagline: 'The rule of thirds: espresso, milk, foam.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 33, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'One third of the cup' },
        { type: 'milk', label: 'Steamed milk', amount: '60 ml', ratio: 33, color: C.milk, sound: 'pour', note: 'The second third' },
        { type: 'foam', label: 'Milk foam', amount: '60 ml', ratio: 34, color: C.foam, sound: 'froth', note: 'A thick, airy cap - the final third' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.espresso, sound: 'blip', note: 'Often finished with a dusting or art' },
      ],
      method: 'Perfect thirds: espresso, steamed milk, and a deep cap of airy foam. The foam is what separates it from a latte.',
      addons: ['cocoa', 'cinnamon', 'vanilla', 'hazelnut', 'caramel', 'decaf', 'extrashot'] },
    { id: 'latte', name: 'Caffè Latte', temp: 'hot', vessel: 'mug', tagline: 'Mostly milk, gently coffee.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 18, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Just one shot in a big cup' },
        { type: 'milk', label: 'Steamed milk', amount: '180 ml', ratio: 64, color: C.milk, sound: 'pour', note: 'The bulk of the drink' },
        { type: 'foam', label: 'Thin foam', amount: '1 cm', ratio: 18, color: C.foam, sound: 'froth', note: 'Only a thin layer on top' },
        { type: 'art', label: 'Latte art', amount: '', ratio: 0, color: C.espresso, sound: 'blip', note: 'The classic canvas for latte art' },
      ],
      method: 'One shot of espresso drowned in steamed milk with just a thin skin of foam. Mild, creamy, and the home of latte art.',
      addons: ['cocoa', 'cinnamon', 'vanilla', 'hazelnut', 'caramel', 'protein', 'decaf', 'extrashot'] },
    { id: 'mocha', name: 'Caffè Mocha', temp: 'hot', vessel: 'mug', tagline: 'A latte that went through chocolate.',
      steps: [
        { type: 'syrup', label: 'Chocolate', amount: '30 ml', ratio: 22, color: C.choc, sound: 'syrup', note: 'Chocolate syrup or melted cocoa in first' },
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 22, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured over the chocolate and stirred' },
        { type: 'milk', label: 'Steamed milk', amount: '120 ml', ratio: 45, color: C.milk, sound: 'pour', note: 'Fills the cup' },
        { type: 'foam', label: 'Foam or cream', amount: 'a cap', ratio: 11, color: C.foam, sound: 'froth', note: 'Finished with foam or whipped cream' },
      ],
      method: 'Chocolate goes in first, espresso melts into it, then steamed milk. A cappuccino and hot chocolate combined.',
      addons: ['cream', 'cocoa', 'caramel', 'hazelnut', 'decaf', 'extrashot'] },
    { id: 'americano', name: 'Americano', temp: 'hot', vessel: 'mug', tagline: 'Espresso, lengthened with hot water.',
      steps: [
        { type: 'espresso', label: 'Espresso', amount: '60 ml', ratio: 38, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'A double shot' },
        { type: 'water', label: 'Hot water', amount: '120 ml', ratio: 62, color: C.water, sound: 'pour', note: 'Hot water stretches it to coffee strength' },
      ],
      method: 'A double espresso diluted with hot water. Same caffeine as the shot, sippable like filter coffee, crema intact.',
      addons: ['cream', 'vanilla', 'decaf', 'extrashot'] },
    { id: 'icedamericano', name: 'Iced Americano', temp: 'cold', vessel: 'highball', tagline: 'Cold, sharp, and straight to the point.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '6 cubes', ratio: 20, color: C.ice, sound: 'clink', note: 'A full glass of ice' },
        { type: 'water', label: 'Cold water', amount: '120 ml', ratio: 45, color: C.water, sound: 'pour', note: 'Cold water over the ice' },
        { type: 'espresso', label: 'Espresso', amount: '60 ml', ratio: 35, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'The shot floats on top, then marbles down' },
      ],
      method: 'Ice and cold water first, espresso poured over the top so it marbles through the glass. Bold and refreshing.',
      addons: ['vanilla', 'caramel', 'decaf', 'extrashot'] },
    { id: 'icedlatte', name: 'Iced Latte', temp: 'cold', vessel: 'highball', tagline: 'Milk over ice, espresso through the middle.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '6 cubes', ratio: 18, color: C.ice, sound: 'clink', note: 'Fill the glass with ice' },
        { type: 'milk', label: 'Cold milk', amount: '150 ml', ratio: 55, color: C.milk, sound: 'pour', note: 'Cold milk straight over the ice' },
        { type: 'espresso', label: 'Espresso', amount: '30 ml', ratio: 27, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured last so it layers on top' },
      ],
      method: 'Ice, cold milk, then the shot poured slowly so it floats in a dark layer before you stir. The most photogenic pour in coffee.',
      addons: ['vanilla', 'hazelnut', 'caramel', 'cream', 'decaf', 'extrashot'] },
    { id: 'coldbrew', name: 'Cold Brew', temp: 'cold', vessel: 'highball', tagline: 'Steeped for 18 hours, never heated.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '4 cubes', ratio: 18, color: C.ice, sound: 'clink', note: 'A few cubes, not a full glass' },
        { type: 'coldbrew', label: 'Cold brew', amount: '200 ml', ratio: 82, color: C.coldbrew, sound: 'pour', note: 'Coarse grounds steeped in cold water for 12-24 hours' },
      ],
      method: 'Coarse coffee steeped in cold water for up to a day, then filtered. Smoother, sweeter, and more caffeinated than iced espresso drinks.',
      addons: ['cream', 'vanilla', 'caramel'] },
    { id: 'frappe', name: 'Frappé', temp: 'cold', vessel: 'highball', tagline: 'Shaken instant coffee with a foam crown.',
      steps: [
        { type: 'ice', label: 'Ice', amount: '4 cubes', ratio: 16, color: C.ice, sound: 'clink', note: 'Ice in the shaker' },
        { type: 'shake', label: 'Coffee + sugar, shaken', amount: '2 tsp', ratio: 0, color: C.frappe, sound: 'shake', note: 'Instant coffee, sugar and a splash of water, shaken hard' },
        { type: 'frappefoam', label: 'Shaken foam', amount: '', ratio: 30, color: '#c8a878', sound: 'froth', note: 'The shake builds a thick, stable foam' },
        { type: 'water', label: 'Cold water', amount: '150 ml', ratio: 54, color: C.water, sound: 'pour', note: 'Topped up with cold water' },
      ],
      method: 'A Greek invention: instant coffee and sugar shaken with ice until it foams, then topped with cold water. The foam is the whole point.',
      addons: ['cream', 'vanilla', 'caramel', 'icecream'] },
    { id: 'affogato', name: 'Affogato', temp: 'cold', vessel: 'glass-small', tagline: 'Ice cream drowned in espresso.',
      steps: [
        { type: 'scoop', label: 'Vanilla ice cream', amount: '1 scoop', ratio: 55, color: '#f3e9d2', sound: 'thud', note: 'A cold scoop in a chilled glass' },
        { type: 'espresso', label: 'Hot espresso', amount: '30 ml', ratio: 45, color: C.espresso, edge: C.crema, sound: 'espresso', note: 'Poured over hot - it "drowns" the scoop' },
      ],
      method: 'Affogato means "drowned". A scoop of vanilla ice cream with a shot of hot espresso poured over it. Dessert and coffee in one.',
      addons: ['cocoa', 'caramel', 'hazelnut', 'extrashot'] },
  ],
  cocktails: [
    { id: 'martini', name: 'Dry Martini', spirit: 'gin', vessel: 'martini', tagline: 'Gin, a whisper of vermouth, ice-cold.',
      steps: [
        { type: 'ice', label: 'Ice in the mixing glass', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Chilled and stirred, never shaken (sorry, Bond)' },
        { type: 'spirit', label: 'Gin', amount: '60 ml', ratio: 78, color: C.gin, sound: 'pour', note: 'London dry, stirred over ice' },
        { type: 'spirit', label: 'Dry vermouth', amount: '10 ml', ratio: 14, color: C.vermouth, sound: 'pour', note: 'Just a whisper - the drier, the less vermouth' },
        { type: 'stir', label: 'Stirred & strained', amount: '30 sec', ratio: 0, color: C.gin, sound: 'stir', note: 'Stirred silky, strained into a frozen coupe' },
        { type: 'garnish-olive', label: 'Olive or lemon twist', amount: '', ratio: 8, color: '#7a8a3a', sound: 'blip', note: 'The garnish is the final word' },
      ],
      method: 'Gin and dry vermouth stirred with ice until freezing, strained into a chilled martini glass, garnished with an olive or a twist of lemon.',
      addons: [] },
    { id: 'mule', name: 'Moscow Mule', spirit: 'vodka', vessel: 'copper', tagline: 'Vodka, ginger beer, lime - in copper.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the mug', ratio: 22, color: C.ice, sound: 'clink', note: 'The copper mug keeps it arctic' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 24, color: C.vodka, sound: 'pour', note: 'Over the ice' },
        { type: 'spirit', label: 'Lime juice', amount: '15 ml', ratio: 8, color: C.lime, sound: 'pour', note: 'Half a lime, squeezed fresh' },
        { type: 'fizz', label: 'Ginger beer', amount: '120 ml', ratio: 46, color: C.gingerbeer, sound: 'fizz', note: 'Spicy ginger beer to the top' },
        { type: 'garnish-lime', label: 'Lime wheel & mint', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'A wheel of lime and a slap of mint' },
      ],
      method: 'Vodka and fresh lime over ice in a copper mug, topped with spicy ginger beer. The copper is not decoration - it keeps the drink colder.',
      addons: [] },
    { id: 'margarita', name: 'Margarita', spirit: 'tequila', vessel: 'margarita', tagline: 'Tequila, lime, triple sec, salt rim.',
      steps: [
        { type: 'rim', label: 'Salt rim', amount: '', ratio: 0, color: '#f0ead8', sound: 'dust', note: 'Lime around the rim, dipped in salt' },
        { type: 'ice', label: 'Ice in the shaker', amount: '', ratio: 0, color: C.ice, sound: 'clink', note: 'Everything goes into the shaker' },
        { type: 'spirit', label: 'Tequila blanco', amount: '50 ml', ratio: 45, color: C.tequila, sound: 'pour', note: '100% agave, always' },
        { type: 'spirit', label: 'Triple sec', amount: '20 ml', ratio: 18, color: C.triplesec, sound: 'pour', note: 'Orange liqueur for sweetness' },
        { type: 'spirit', label: 'Lime juice', amount: '25 ml', ratio: 22, color: C.lime, sound: 'pour', note: 'Fresh lime, no exceptions' },
        { type: 'shake', label: 'Shaken hard', amount: '15 sec', ratio: 0, color: C.tequila, sound: 'shake', note: 'Shake until the tin frosts' },
        { type: 'strain', label: 'Strained over ice', amount: '', ratio: 15, color: '#e4e0c0', sound: 'pour', note: 'Fine-strained into the salted glass' },
        { type: 'garnish-lime', label: 'Lime wheel', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'On the rim' },
      ],
      method: 'Tequila, triple sec and fresh lime shaken hard with ice, strained into a salt-rimmed glass. Sour, cold, and balanced.',
      addons: [] },
    { id: 'screwdriver', name: 'Screwdriver', spirit: 'vodka', vessel: 'highball', tagline: 'Vodka and orange juice. That is it.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 20, color: C.ice, sound: 'clink', note: 'A highball full of ice' },
        { type: 'spirit', label: 'Vodka', amount: '50 ml', ratio: 28, color: C.vodka, sound: 'pour', note: 'Over the ice' },
        { type: 'juice', label: 'Orange juice', amount: '120 ml', ratio: 52, color: C.oj, sound: 'pour', note: 'Fresh squeezed if you can' },
        { type: 'garnish-orange', label: 'Orange slice', amount: '', ratio: 0, color: C.oj, sound: 'blip', note: 'A slice on the rim' },
      ],
      method: 'Two ingredients over ice: vodka and orange juice, stirred once. Named by oil workers who stirred it with screwdrivers.',
      addons: [] },
    { id: 'jagerbomb', name: 'Jägerbomb', spirit: 'other', vessel: 'bomb', tagline: 'A shot of Jäger dropped into energy drink.',
      steps: [
        { type: 'fizz', label: 'Energy drink', amount: '150 ml', ratio: 70, color: C.energy, sound: 'fizz', note: 'Half a can, ice cold, in the glass' },
        { type: 'shotglass', label: 'Jägermeister shot', amount: '30 ml', ratio: 30, color: C.jager, sound: 'pour', note: 'A full shot, poured separately' },
        { type: 'drop', label: 'The drop', amount: '', ratio: 0, color: C.jager, sound: 'splash', note: 'Drop the shot in and drink immediately' },
      ],
      method: 'A shot of ice-cold Jägermeister dropped into a glass of energy drink. The drop mixes it at the table. Built for toasts, not sipping.',
      addons: [] },
    { id: 'mojito', name: 'Mojito', spirit: 'rum', vessel: 'highball', tagline: 'Mint, lime, rum, soda - muddled fresh.',
      steps: [
        { type: 'garnish-mint', label: 'Mint leaves', amount: '8 leaves', ratio: 6, color: C.mint, sound: 'blip', note: 'Slapped, not shredded' },
        { type: 'sugar', label: 'Sugar + lime', amount: '2 tsp + half a lime', ratio: 8, color: C.sugar, sound: 'dust', note: 'Muddled gently with the mint' },
        { type: 'ice', label: 'Crushed ice', amount: 'fill', ratio: 24, color: C.ice, sound: 'clink', note: 'Crushed, not cubed' },
        { type: 'spirit', label: 'White rum', amount: '50 ml', ratio: 30, color: C.rum, sound: 'pour', note: 'Over the ice' },
        { type: 'fizz', label: 'Soda water', amount: 'top up', ratio: 32, color: C.soda, sound: 'fizz', note: 'Topped with soda and lifted with a spoon' },
        { type: 'garnish-mint', label: 'Mint sprig', amount: '', ratio: 0, color: C.mint, sound: 'blip', note: 'A big sprig so you smell it first' },
      ],
      method: 'Mint and lime muddled with sugar, white rum over crushed ice, topped with soda. Cuba in a glass.',
      addons: [] },
    { id: 'oldfashioned', name: 'Old Fashioned', spirit: 'whiskey', vessel: 'rocks', tagline: 'Whiskey, sugar, bitters. The original cocktail.',
      steps: [
        { type: 'sugar', label: 'Sugar cube + bitters', amount: '1 cube, 2 dashes', ratio: 6, color: C.sugar, sound: 'dust', note: 'Bitters soaked into the cube, muddled' },
        { type: 'iceblock', label: 'One big ice block', amount: '', ratio: 26, color: C.ice, sound: 'clink', note: 'One large cube - it melts slow' },
        { type: 'spirit', label: 'Bourbon or rye', amount: '60 ml', ratio: 60, color: C.whiskey, sound: 'pour', note: 'Poured over the ice, stirred briefly' },
        { type: 'garnish-orange', label: 'Orange peel', amount: '', ratio: 8, color: '#d8842a', sound: 'blip', note: 'Expressed over the glass, oils and all' },
      ],
      method: 'A sugar cube soaked in bitters, muddled, one large ice block, and good whiskey stirred over it. The template every cocktail descends from.',
      addons: [] },
    { id: 'gintonic', name: 'Gin & Tonic', spirit: 'gin', vessel: 'highball', tagline: 'Two ingredients, endless ritual.',
      steps: [
        { type: 'ice', label: 'Ice cubes', amount: 'fill the glass', ratio: 22, color: C.ice, sound: 'clink', note: 'Lots of ice - it melts slower' },
        { type: 'spirit', label: 'Gin', amount: '50 ml', ratio: 26, color: C.gin, sound: 'pour', note: 'London dry over the ice' },
        { type: 'fizz', label: 'Tonic water', amount: '150 ml', ratio: 52, color: C.tonic, sound: 'fizz', note: 'Poured gently to keep the fizz' },
        { type: 'garnish-lime', label: 'Lime wedge', amount: '', ratio: 0, color: C.lime, sound: 'blip', note: 'Squeezed and dropped in' },
      ],
      method: 'Gin over a glass packed with ice, topped with tonic poured down the side to keep the bubbles, finished with lime.',
      addons: [] },
  ],
};

export const MODE_META = {
  coffee: {
    title: 'COFFEE', accent: '#e09543',
    headline: 'What is a cappuccino, actually?',
    sub: 'Pick one. Watch it get built - every pour, in order, with sound.',
    filters: [ { id: 'all', label: 'ALL' }, { id: 'hot', label: 'HOT' }, { id: 'cold', label: 'COLD' } ],
    filterKey: 'temp', filterPrompt: 'First: hot or cold?',
    addonsTitle: 'Make it yours',
  },
  cocktails: {
    title: 'COCKTAILS', accent: '#c6f24e',
    headline: 'What goes into the glass?',
    sub: 'The right glass, the right ice, the shake, the pour, the garnish.',
    filters: [ { id: 'all', label: 'ALL' }, { id: 'gin', label: 'GIN' }, { id: 'vodka', label: 'VODKA' }, { id: 'rum', label: 'RUM' }, { id: 'tequila', label: 'TEQUILA' }, { id: 'whiskey', label: 'WHISKEY' }, { id: 'other', label: 'OTHER' } ],
    filterKey: 'spirit', filterPrompt: 'Pick your spirit',
    addonsTitle: null,
  },
};
